document.write ("<div class='tm-main-content'>");
	document.write ("<section class='tm-margin-b-l'>");
		document.write ("<header>");
			document.write ("<a href='#联系我们'></a>");
			document.write ("<h2 class='tm-main-title'>联系我们</h2>");  
		document.write ("</header>");
		document.write ("<div class='tm-gallery'>");
			document.write ("<div class='row'>");
				document.write ("<figure class='col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item'>");
						document.write ("<div class='text'><img alt='' src='img/zqsm.jpg' style='width:100%; height:100%;' />1.咨询请搜索微信号：zhangqiaoshuma</div>");
				document.write ("</figure>");
				document.write ("</br>");
				document.write ("<figure class='col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item'>");
						document.write ("<div class='text'><img alt='' src='img/xiaoshangdian.jpg' style='width:100%; height:100%;' />2.扫描二维码进入微信小店</div>");
				document.write ("</figure>");
			document.write ("</div> ");
			document.write ("<div class='row'>");
				document.write ("<figure class='col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item'>");
					document.write ("<div class='text center'><img alt='' src='img/zhangqiaohome1.jpg' style='width:100%; height:200%;' />3.激活方法请关注【张桥之家】公众号:zhangqiaohome</div>");
				document.write ("</figure>");
			document.write ("</div> ");
		document.write ("</div>");
	document.write ("</section>");
document.write ("</div>");